name: Continuous Integration Build

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI Build
    runs-on: windows-latest

    strategy:
      matrix:
        os: [windows-latest]
        node-version: [14.x]
        dotnet: [ '6.0.x' ]

    steps:
    - name: Install MS SQL local db
      uses: potatoqualitee/mssqlsuite@v1.5.1
      with:
        install: localdb
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup .NET ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Install Dotnet Tools
      run: dotnet tool restore
    - name: Run migrations
      run:  dotnet run RunMigrations --project .\devops\Build\Build.fsproj
    - name: Build application
      run: dotnet run Build --project .\devops\Build\Build.fsproj
